---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "981d792025b8571b35351eee6a2ca96a2a0dac03"
    fabric8.io/git-branch: "master"
    fabric8.io/git-url: "https://github.com/mustafamehdi/camel_xml_dsl.git"
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: "camel-ose-springboot-xml"
    provider: "fabric8"
    version: "1.0.0-SNAPSHOT"
    group: "org.mycompany"
  name: "camel-ose-springboot-xml"
spec:
  ports:
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "camel-ose-springboot-xml"
    provider: "fabric8"
    group: "org.mycompany"
